Buildings.new(:name => "Adair").save
Buildings.new(:name => "Andrews").save
Buildings.new(:name => "Blow").save
Buildings.new(:name => "Bozarth").save
Buildings.new(:name => "Center for Archaeological Research").save
Buildings.new(:name => "Ceramics Studio").save
Buildings.new(:name => "Endocrinology Lab").save
Buildings.new(:name => "Ewell").save
Buildings.new(:name => "ISC1").save
Buildings.new(:name => "ISC2").save
Buildings.new(:name => "James Blair ").save
Buildings.new(:name => "Jones").save
Buildings.new(:name => "Keck").save
Buildings.new(:name => "Law School").save
Buildings.new(:name => "Matoaka Art Studio").save
Buildings.new(:name => "McGlothlin-Street Hall").save
Buildings.new(:name => "Miller").save
Buildings.new(:name => "Millington").save
Buildings.new(:name => "Morton").save
Buildings.new(:name => "PBK Hall").save
Buildings.new(:name => "Prince George House").save
Buildings.new(:name => "Small").save
Buildings.new(:name => "School Of Education").save
Buildings.new(:name => "Tucker").save
Buildings.new(:name => "Tyler").save
Buildings.new(:name => "Washington").save
Buildings.new(:name => "Wren").save
Buildings.new(:name => "Barrett").save
Buildings.new(:name => "Brown").save
Buildings.new(:name => "Bryan").save
Buildings.new(:name => "Cabell").save
Buildings.new(:name => "Camm").save
Buildings.new(:name => "Campus Center").save
Buildings.new(:name => "Chandler ").save
Buildings.new(:name => "Commons Dining Hall").save
Buildings.new(:name => "Dawson").save
Buildings.new(:name => "Dinwiddie").save
Buildings.new(:name => "Dupont").save
Buildings.new(:name => "Fauquier").save
Buildings.new(:name => "Giles").save
Buildings.new(:name => "Gooch").save
Buildings.new(:name => "Graduate Housing Complex").save
Buildings.new(:name => "Harrison").save
Buildings.new(:name => "Hughes").save
Buildings.new(:name => "Hunt").save
Buildings.new(:name => "Jamestown North").save
Buildings.new(:name => "Jamestown South").save
Buildings.new(:name => "Jefferson ").save
Buildings.new(:name => "Landrum").save
Buildings.new(:name => "Lodge 2").save
Buildings.new(:name => "Lodge 4").save
Buildings.new(:name => "Lodge 6").save
Buildings.new(:name => "Lodge 8").save
Buildings.new(:name => "Lodge 10").save
Buildings.new(:name => "Lodge 12").save
Buildings.new(:name => "Lodge 16").save
Buildings.new(:name => "Ludwell Apts").save
Buildings.new(:name => "Madison").save
Buildings.new(:name => "Meridian Coffee House").save
Buildings.new(:name => "Monroe ").save
Buildings.new(:name => "Munford").save
Buildings.new(:name => "Nicholas").save
Buildings.new(:name => "Nicholson").save
Buildings.new(:name => "Old Dominion ").save
Buildings.new(:name => "Page").save
Buildings.new(:name => "Pleasants").save
Buildings.new(:name => "Preston").save
Buildings.new(:name => "Reves Hall").save
Buildings.new(:name => "Sadler Center ").save
Buildings.new(:name => "Sor 1: KKG").save
Buildings.new(:name => "Sor 2: ACO").save
Buildings.new(:name => "Sor 3: CO").save
Buildings.new(:name => "Sor 4: DDD").save
Buildings.new(:name => "Sor 5: PBP").save
Buildings.new(:name => "Sor 6: KD").save
Buildings.new(:name => "Sor 7: DG").save
Buildings.new(:name => "Sor 8: PM").save
Buildings.new(:name => "Sor 9: KAT").save
Buildings.new(:name => "Sor 10: Bozzarth").save
Buildings.new(:name => "Sor 11: GPB").save
Buildings.new(:name => "Sor 12: DP(Mullen)").save
Buildings.new(:name => "Spotswood").save
Buildings.new(:name => "Stith").save
Buildings.new(:name => "Taliaferro").save
Buildings.new(:name => "Tazewell").save
Buildings.new(:name => "Tribe Square").save
Buildings.new(:name => "Units (specify letter in room number)").save
Buildings.new(:name => "Yates").save
