require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkordersController do

  # This should return the minimal set of attributes required to create a valid
  # Workorder. As you add validations to Workorder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "description" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkordersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all workorders as @workorders" do
      workorder = Workorder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:workorders).should eq([workorder])
    end
  end

  describe "GET show" do
    it "assigns the requested workorder as @workorder" do
      workorder = Workorder.create! valid_attributes
      get :show, {:id => workorder.to_param}, valid_session
      assigns(:workorder).should eq(workorder)
    end
  end

  describe "GET new" do
    it "assigns a new workorder as @workorder" do
      get :new, {}, valid_session
      assigns(:workorder).should be_a_new(Workorder)
    end
  end

  describe "GET edit" do
    it "assigns the requested workorder as @workorder" do
      workorder = Workorder.create! valid_attributes
      get :edit, {:id => workorder.to_param}, valid_session
      assigns(:workorder).should eq(workorder)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Workorder" do
        expect {
          post :create, {:workorder => valid_attributes}, valid_session
        }.to change(Workorder, :count).by(1)
      end

      it "assigns a newly created workorder as @workorder" do
        post :create, {:workorder => valid_attributes}, valid_session
        assigns(:workorder).should be_a(Workorder)
        assigns(:workorder).should be_persisted
      end

      it "redirects to the created workorder" do
        post :create, {:workorder => valid_attributes}, valid_session
        response.should redirect_to(Workorder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved workorder as @workorder" do
        # Trigger the behavior that occurs when invalid params are submitted
        Workorder.any_instance.stub(:save).and_return(false)
        post :create, {:workorder => { "description" => "invalid value" }}, valid_session
        assigns(:workorder).should be_a_new(Workorder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Workorder.any_instance.stub(:save).and_return(false)
        post :create, {:workorder => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested workorder" do
        workorder = Workorder.create! valid_attributes
        # Assuming there are no other workorders in the database, this
        # specifies that the Workorder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Workorder.any_instance.should_receive(:update_attributes).with({ "description" => "MyString" })
        put :update, {:id => workorder.to_param, :workorder => { "description" => "MyString" }}, valid_session
      end

      it "assigns the requested workorder as @workorder" do
        workorder = Workorder.create! valid_attributes
        put :update, {:id => workorder.to_param, :workorder => valid_attributes}, valid_session
        assigns(:workorder).should eq(workorder)
      end

      it "redirects to the workorder" do
        workorder = Workorder.create! valid_attributes
        put :update, {:id => workorder.to_param, :workorder => valid_attributes}, valid_session
        response.should redirect_to(workorder)
      end
    end

    describe "with invalid params" do
      it "assigns the workorder as @workorder" do
        workorder = Workorder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Workorder.any_instance.stub(:save).and_return(false)
        put :update, {:id => workorder.to_param, :workorder => { "description" => "invalid value" }}, valid_session
        assigns(:workorder).should eq(workorder)
      end

      it "re-renders the 'edit' template" do
        workorder = Workorder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Workorder.any_instance.stub(:save).and_return(false)
        put :update, {:id => workorder.to_param, :workorder => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested workorder" do
      workorder = Workorder.create! valid_attributes
      expect {
        delete :destroy, {:id => workorder.to_param}, valid_session
      }.to change(Workorder, :count).by(-1)
    end

    it "redirects to the workorders list" do
      workorder = Workorder.create! valid_attributes
      delete :destroy, {:id => workorder.to_param}, valid_session
      response.should redirect_to(workorders_url)
    end
  end

end
